### PR TITLE
Added o/oladad.md

### PR DESCRIPTION
**Pull request by vahona**
Hey, 
This is my new file, please have a look! 
Feel free to ask changes if need to be.

thank you so much
Sugi

### CODE REVIEW

**Review by ndorfin — CHANGES_REQUESTED** [review]
Great find! I'd suggest updating the genre, and moving it under the bio.

**Comment by vahona** [comment]
Hi,
I've done the change, please have a look

**Review by ndorfin — CHANGES_REQUESTED** [review]
Missing an image!

**Comment by vahona** [comment]
Hey! 
I think it is already fine now

**Pull request closed without merging**
