### PR TITLE
Fixing firmin

### PR DESCRIPTION
**Pull request by Tiaraha-funny**
Hey,
I have fixed it, have a look please. Happy to change if needs.
Thanks.

### CODE REVIEW

**Review by ndorfin — CHANGES_REQUESTED** [review]
Make the image use the correct filename please

**Comment by Tiaraha-funny** [comment]
I have fixed the image. Please have a look.

**Review by ndorfin — CHANGES_REQUESTED** [review]
please delete `f/fir.jog`

**Review by ndorfin — APPROVED** [review]
Nice work!

**Pull request merged**
