### PR TITLE
Added Denise

### PR DESCRIPTION
**Pull request by Tsikitsiky**
Hey,
This is my first artist, please have a look.

Thank you
Sarah

### CODE REVIEW

**Review by ndorfin — CHANGES_REQUESTED** [review]
please remove the duplicate `DENISE.jpg`

**Comment by Tsikitsiky** [comment]
Hi,
I think I've made the change, please check

**Review by ndorfin — CHANGES_REQUESTED** [review]
Make the filename for the image lowercase too please.

**Comment by Tsikitsiky** [comment]
Hi,
Here is the change you've requested, please have a look.

**Review by ndorfin — APPROVED** [review]

**Pull request merged**
